### ISSUE TITLE
io.github.vishalmysore:tools4ai:jar:1.0.1 is missing, no dependency information available

### ISSUE THREAD

**Issue by ffazil** [vishalmysore/simplelam#1]
````
<dependency>
            <groupId>io.github.vishalmysore</groupId>
            <artifactId>tools4ai</artifactId>
            <version>1.0.1</version>
        </dependency>
````

- Tools4AI version 1.0.1 is not available in maven. 
- Tools4AI version 1.0.0 is available, however `SeleniumGeminiProcessor` class is missing.

**Comment by vishalmysore** [comment]
Hey , its available now , Thanks for your feedback , also please note that that SeleniumProcessor has been refactored and now there are two implementations
- SeleniumGeminiProcessor
with image capabilities 

- SeleniumOpenAIProcessor
with html parsing

Also as you would notice looking at the code of Tools4AI this class is work in progress as I have to identify each various permutation and combination of selenium actions, right now it works for GET, CLICK , Get Element etc,

**Comment by ffazil** [comment]
Thanks for the update. Will check it out and open issues if necessary.
